export const GET_PLUGINS = 'GET_PLUGINS';
export const GET_PLUGINS_BY_TAG = 'GET_PLUGINS_BY_TAG';
export const GET_PLUGINS_BY_KEYWORD = 'GET_PLUGINS_BY_KEYWORD';
export const ADD_PLUGIN = 'ADD_PLUGIN';

export const LOADING_PLUGIN = 'LOADING_PLUGIN';
export const GET_PLUGINS_BY_ID = 'GET_PLUGINS_BY_ID';

export const ADD_USER = 'ADD_USER';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOADING_USER_DATA = 'LOADING_USER_DATA';
export const GET_MY_PLUGINS = 'GET_MY_PLUGINS';
export const GET_PLUGIN_TO_MODIFY = 'GET_PLUGIN_TO_MODIFY';
export const MODIFY_PLUGIN = 'MODIFY_PLUGIN';
export const ADD_PLUGIN_PARAMETRE = 'MODIFY_PLUGIN_PARAMETRE';
export const DELETE_PLUGIN_PARAMETRE = 'DELETE_PLUGIN_PARAMETRE';
export const ADD_PLUGIN_TAG = 'ADD_PLUGIN_TAG';
export const DELETE_PLUGIN_TAG = 'DELETE_PLUGIN_TAG';
export const DELETE_PLUGIN = 'DELETE_PLUGIN';